[package]
name = "matcha"
version = "0.1.1"
authors = ["MC mattscamp@gmail.com"]
description = "Useful string search algorithms"
repository = "https://github.com/mattscamp/matcha"
keywords = ["search", "string", "tbm", "boyer", "moore"]
license = "MIT"

[dependencies]
memcmp = "0.0.6"